services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    volumes:
      - ./localstack-setup.sh:/etc/localstack/init/ready.d/script.sh

    environment:
      - DEBUG=1
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}
      - EXTRA_CORS_ALLOWED_ORIGINS=*


volumes:
  localstack-data:
